
const state={activeTab:"arbeid",loggedIn:false,calculated:false,score:0,level:""};
const labels={arbeid:"Arbeidsuitbuiting",seksueel:"Seksuele uitbuiting",crimineel:"Criminele uitbuiting",algemeen:"Algemene signalen",context:"Bestuurlijke en contextuele signalen"};
const contacts={low:["Leg de casus intern vast en bespreek deze met een relevante collega of regiehouder.","Fictief contact: Team OOV – oov-demo@emmen.nl"],mid:["Bespreek de casus in een intern of multidisciplinair overleg en verrijk het beeld.","Fictief contact: Aandachtsfunctionaris Mensenhandel – mensenhandel-demo@emmen.nl","Fictief contact: Regie / Veiligheidscoördinatie – regie-demo@emmen.nl"],high:["Zet de casus met voorrang door naar de passende ketenpartners en leg regie vast.","Fictief contact: AVIM / Politie – avim-demo@keten.nl","Fictief contact: Arbeidsinspectie – arbeidsinspectie-demo@keten.nl","Fictief contact: Zorg- en Veiligheidshuis – zvh-demo@keten.nl"]};
function selectedSignals(){return Array.from(document.querySelectorAll(".signal-check:checked")).map(el=>({group:el.dataset.group,text:el.value}));}
function renderTabs(){const tabs=document.getElementById("tabs");tabs.innerHTML="";Object.keys(window.SIGNAL_DATA).forEach(key=>{const b=document.createElement("button");b.className="tab-btn"+(state.activeTab===key?" active":"");b.textContent=labels[key];b.type="button";b.onclick=()=>{state.activeTab=key;renderTabs();renderSignals();};tabs.appendChild(b);});}
function renderSignals(){const list=document.getElementById("signalList");list.innerHTML="";(window.SIGNAL_DATA[state.activeTab]||[]).forEach((text,idx)=>{const id=`${state.activeTab}_${idx}`;const row=document.createElement("label");row.className="signal-item";row.innerHTML=`<input class="signal-check" type="checkbox" id="${id}" data-group="${labels[state.activeTab]}" value="${text}"><div><strong>${text}</strong><div class="muted-note">${labels[state.activeTab]}</div></div>`;list.appendChild(row);});document.querySelectorAll(".signal-check").forEach(cb=>cb.addEventListener("change",syncKpis));}
function calcScore(){const sel=selectedSignals();const count=sel.length;let score=0;sel.forEach(s=>{if(s.group.includes("Algemene"))score+=2;else if(s.group.includes("Bestuurlijke"))score+=2;else score+=3;});let level="low";if(score>=18||count>=7)level="high";else if(score>=9||count>=4)level="mid";state.calculated=true;state.score=score;state.level=level;const scoreValue=document.getElementById("scoreValue");const scoreBadge=document.getElementById("scoreBadge");const scoreDetails=document.getElementById("scoreDetails");const adviceList=document.getElementById("adviceList");scoreValue.textContent=String(score);if(level==="high"){scoreBadge.className="badge badge-high";scoreBadge.textContent="Hoog risico";}else if(level==="mid"){scoreBadge.className="badge badge-mid";scoreBadge.textContent="Verhoogd risico";}else{scoreBadge.className="badge badge-low";scoreBadge.textContent="Laag risico";}scoreDetails.innerHTML=`<li>Aantal geselecteerde signalen: ${count}</li><li>Gewogen score: ${score}</li><li>Classificatie: ${scoreBadge.textContent}</li>`;const adv=[...contacts[level]];if(state.loggedIn)adv.push("Fictief telefoonoverzicht na login: 06-1843 5521 / 06-2741 6638 / 06-3819 4472");adviceList.innerHTML=adv.map(item=>`<li>${item}</li>`).join("");syncKpis();}
function escapeHtml(text){const div=document.createElement("div");div.innerText=text;return div.innerHTML;}
function buildReportHtml(){const now=new Date();const date=now.toLocaleDateString("nl-NL");const time=now.toLocaleTimeString("nl-NL",{hour:"2-digit",minute:"2-digit"});const adres=document.getElementById("adres").value||"-";const typeCasus=document.getElementById("typeCasus").value||"-";const focus=document.getElementById("focus").value||"-";const bevindingen=document.getElementById("bevindingen").value||"-";const observaties=document.getElementById("observaties").value||"-";const sel=selectedSignals();const summary=state.calculated?`De signalencheck is uitgevoerd op ${date} om ${time}. De casus is ingeschat als ${document.getElementById("scoreBadge").textContent.toLowerCase()} met een score van ${state.score}.`:`De rapportage is opgesteld op ${date} om ${time}. De risicoscore is nog niet berekend.`;const advice=document.getElementById("adviceList").innerHTML||"<li>Nog geen advies beschikbaar.</li>";return `<div class="report-block"><h4>Samenvatting</h4><p>${summary}</p></div><div class="report-block"><h4>Datum en tijdstip</h4><p>${date} • ${time}</p></div><div class="report-block"><h4>Basisgegevens</h4><p><strong>Locatie / adres:</strong> ${adres}<br><strong>Type casus / controle:</strong> ${typeCasus}<br><strong>Primair vermoed type uitbuiting:</strong> ${focus}</p></div><div class="report-block"><h4>Bevindingen</h4><p>${escapeHtml(bevindingen).replace(/\n/g,"<br>")}</p></div><div class="report-block"><h4>Observaties</h4><p>${escapeHtml(observaties).replace(/\n/g,"<br>")}</p></div><div class="report-block"><h4>Geselecteerde signalen</h4>${sel.length?`<ul class="list">${sel.map(s=>`<li><strong>${s.group}:</strong> ${escapeHtml(s.text)}</li>`).join("")}</ul>`:'<p class="muted-note">Nog geen signalen geselecteerd.</p>'}</div><div class="report-block"><h4>Risicoscore</h4><p>${state.calculated?`${state.score} • ${document.getElementById("scoreBadge").textContent}`:"Nog niet berekend"}</p></div><div class="report-block"><h4>Doorzetadvies</h4><ul class="list">${advice}</ul></div>`;}
function updateReport(){document.getElementById("reportPreview").innerHTML=buildReportHtml();}
function downloadReport(){updateReport();const now=new Date();const timestamp=now.toISOString().slice(0,16).replace(/[:T]/g,"-");const text=document.getElementById("reportPreview").innerText;const blob=new Blob([text],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`rapportage_signalencheck_${timestamp}.txt`;a.click();URL.revokeObjectURL(a.href);}
function resetCheck(){document.querySelectorAll(".signal-check").forEach(cb=>cb.checked=false);document.getElementById("adres").value="";document.getElementById("bevindingen").value="";document.getElementById("observaties").value="";state.calculated=false;state.score=0;state.level="";document.getElementById("scoreValue").textContent="Nog niet berekend";document.getElementById("scoreBadge").className="badge badge-low";document.getElementById("scoreBadge").textContent="Nog niet berekend";document.getElementById("scoreDetails").innerHTML='<li>Selecteer eerst de relevante signalen en klik daarna op “Bereken uitkomst”.</li>';document.getElementById("adviceList").innerHTML="<li>Na berekening verschijnt hier het vervolgadvies.</li>";document.getElementById("reportPreview").innerHTML='<div class="report-block"><h4>Samenvatting</h4><p class="muted-note">Nog niet opgesteld.</p></div>';syncKpis();}
function syncKpis(){document.getElementById("kpiSignals").textContent=String(selectedSignals().length);document.getElementById("kpiScore").textContent=state.calculated?String(state.score):"-";document.getElementById("kpiStatus").textContent=state.calculated?"Berekenend":"Nieuw";document.getElementById("kpiLogin").textContent=state.loggedIn?"Ja":"Nee";}
function setupLogin(){const overlay=document.getElementById("loginOverlay");document.getElementById("loginBtn").onclick=()=>overlay.classList.add("show");document.getElementById("closeLogin").onclick=()=>overlay.classList.remove("show");document.getElementById("submitLogin").onclick=()=>{const u=document.getElementById("userName").value.trim();const p=document.getElementById("passWord").value.trim();const msg=document.getElementById("loginMsg");if(u==="SDEV1"&&p==="12345"){state.loggedIn=true;msg.textContent="Inloggen gelukt. Aanvullende doorzetinformatie is actief.";overlay.classList.remove("show");if(state.calculated)calcScore();syncKpis();}else{msg.textContent="Onjuiste inloggegevens. Gebruik voor deze demo: SDEV1 / 12345.";}};}
function setupMenu(){const btn=document.getElementById("menuBtn");const panel=document.getElementById("menuPanel");btn.onclick=()=>panel.classList.toggle("open");document.addEventListener("click",e=>{if(!panel.contains(e.target)&&e.target!==btn)panel.classList.remove("open");});document.getElementById("newCheckMenu").onclick=()=>{resetCheck();panel.classList.remove("open");};}
document.addEventListener("DOMContentLoaded",()=>{renderTabs();renderSignals();setupLogin();setupMenu();document.getElementById("calcBtn").onclick=calcScore;document.getElementById("reportBtn").onclick=updateReport;document.getElementById("downloadBtn").onclick=downloadReport;document.getElementById("printBtn").onclick=()=>window.print();document.getElementById("resetBtn").onclick=resetCheck;syncKpis();});
