/* Signalencheck v4 — app-router, gecombineerde waarnemingen, overzicht en instellingen. */
(function(){
  "use strict";
  const M=window.SignalenModel;const catalog=window.APP_OBSERVATIONS;let state=M.createState(catalog);
  const $=id=>document.getElementById(id),all=sel=>[...document.querySelectorAll(sel)];
  const SETTINGS_KEY="signalencheck-settings-v4",HISTORY_KEY="signalencheck-history-v4";let installPrompt=null;let settings=loadSettings();
  function loadSettings(){try{return {...{theme:"light",pushNotifications:false,inAppNotifications:true},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")};}catch(_){return {theme:"light",pushNotifications:false,inAppNotifications:true};}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
  function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");}catch(_){return [];}}
  function saveHistory(items){localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,25)));}
  function applyTheme(){document.documentElement.dataset.theme=settings.theme==="dark"?"dark":"light";const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=settings.theme==="dark"?"#11151d":"#e30613";all('input[name="theme"]').forEach(el=>el.checked=el.value===settings.theme);}
  function showToast(message){if(!settings.inAppNotifications)return;const toast=$("toast");toast.textContent=message;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,2600);}
  async function showBrowserNotification(message){if(!settings.pushNotifications||!("Notification" in window)||Notification.permission!=="granted")return;try{if("serviceWorker" in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification("Signalencheck Mensenhandel",{body:message,icon:"./icons/icon-192.png",tag:"signalencheck-local"});}else new Notification("Signalencheck Mensenhandel",{body:message});}catch(_){}}
  function showView(id){all(".app-view").forEach(v=>v.hidden=v.id!==id);all("[data-mobile]").forEach(btn=>btn.classList.toggle("active",btn.dataset.mobile===id));if(id==="observationsView"){renderObservations();renderProfiles();}if(id==="overviewView")renderHistory();if(id==="reportView")renderReport();if(id==="settingsView")syncSettingsUi();updateSummary();window.scrollTo({top:0,behavior:"smooth"});}
  function goHome(){showView("homeView");}
  function bindContext(){all("[data-context]").forEach(el=>{const key=el.dataset.context;if(!Object.hasOwn(state.context,key))return;el.value=state.context[key];const handler=()=>{M.setContext(state,key,el.value);if(key==="acuteConcern")$("acuteNotice").hidden=el.value!=="yes";updateSummary();};el.addEventListener("input",handler);el.addEventListener("change",handler);});}
  function syncContext(){all("[data-context]").forEach(el=>{const key=el.dataset.context;if(Object.hasOwn(state.context,key))el.value=state.context[key];});$("acuteNotice").hidden=state.context.acuteConcern!=="yes";}
  function renderProfiles(targetId="profileCards"){const host=$(targetId);if(!host)return;host.replaceChildren();for(const p of M.profile(state,catalog)){const card=document.createElement("article");card.className="profile-card";const val=p.match===null?"—":p.match+"%",width=p.match===null?0:p.match;card.innerHTML=`<h3>${p.title}</h3><div class="profile-value">${val}</div><div class="profile-meta">${p.label} · ${p.assessedCount}/${p.totalRelevant} relevante waarnemingen beoordeeld</div><div class="profile-bar"><span style="width:${width}%"></span></div>`;host.appendChild(card);}}
  function createChoiceButton(item,status,value,label,group){const b=document.createElement("button");b.type="button";b.dataset.value=value;b.textContent=label;b.classList.toggle("active",status===value);b.addEventListener("click",()=>{M.setAnswer(state,item.id,value,state.answers[item.id].note);[...group.children].forEach(x=>x.classList.toggle("active",x===b));renderProfiles();updateObservationProgress();updateSummary();});return b;}
  function renderObservations(){const host=$("observationsMount");host.replaceChildren();let current=null;for(const item of catalog){if(item.type!==current){current=item.type;const h=document.createElement("div");h.className="observation-section-label";h.textContent=current==="environment"?"Omgevings- en dossierinformatie":"Feitelijke mogelijke waarnemingen";host.appendChild(h);}const row=document.createElement("div");row.className="observation-row";const left=document.createElement("div"),text=document.createElement("div");text.className="observation-text";text.textContent=item.text;const note=document.createElement("details");note.className="observation-note";note.innerHTML='<summary>Toelichting / feitelijke bron</summary>';const ta=document.createElement("textarea");ta.rows=2;ta.placeholder="Beschrijf kort waarop de beoordeling is gebaseerd.";ta.value=state.answers[item.id].note;ta.addEventListener("input",()=>M.setAnswer(state,item.id,state.answers[item.id].status,ta.value));note.appendChild(ta);left.append(text,note);const group=document.createElement("div");group.className="choice-group";group.setAttribute("role","group");group.setAttribute("aria-label",item.text);const status=state.answers[item.id].status;group.append(createChoiceButton(item,status,"yes","Ja",group),createChoiceButton(item,status,"no","Nee",group),createChoiceButton(item,status,"unknown","Niet beoordeeld",group));row.append(left,group);host.appendChild(row);}updateObservationProgress();}
  function updateObservationProgress(){const c=M.counts(state,catalog);$("observationProgress").textContent=`${c.yes+c.no} van ${catalog.length} beoordeeld · ${c.yes} ja`;}
  function updateSummary(){const c=M.counts(state,catalog);$("summaryAssessed").textContent=`${c.yes+c.no} / ${catalog.length}`;$("summaryYes").textContent=c.yes;$("summaryLocation").textContent=state.context.location.trim()||"Niet ingevuld";$("sessionStatus").textContent=state.dirty?"Check in bewerking":"Nieuwe check";$("versionLabel").textContent=M.VERSION;}
  function clearObservations(){if(!confirm("Alle beoordelingen uit de waarnemingenlijst wissen?"))return;catalog.forEach(item=>M.setAnswer(state,item.id,"unknown",""));renderObservations();renderProfiles();updateSummary();showToast("Waarnemingen gewist.");}
  function snapshotSummary(){const snap=M.createSnapshot(state,catalog);return {id:(state.context.caseCode.trim()||"CHECK")+"-"+Date.now(),caseCode:state.context.caseCode.trim()||"Geen zaakcode",observedAt:state.context.observedAt||snap.generatedAt,location:state.context.location.trim()||"Niet ingevuld",savedAt:snap.generatedAt,yesCount:snap.counts.yes,assessedCount:snap.counts.yes+snap.counts.no,profiles:snap.profiles.map(p=>({id:p.id,title:p.title,match:p.match,label:p.label}))};}
  async function saveCurrentCheck(){const history=loadHistory();history.unshift(snapshotSummary());saveHistory(history);showToast("Check lokaal opgeslagen in Overzicht.");await showBrowserNotification("De check is lokaal toegevoegd aan Overzicht.");state.dirty=false;updateSummary();renderHistory();}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
  function renderHistory(){const host=$("historyList"),items=loadHistory();host.replaceChildren();$("historyCount").textContent=`${items.length} ${items.length===1?"check":"checks"}`;if(!items.length){const e=document.createElement("div");e.className="history-empty";e.textContent="Nog geen afgeronde checks opgeslagen op dit apparaat.";host.appendChild(e);return;}items.forEach(item=>{const row=document.createElement("article");row.className="history-item";const main=document.createElement("div"),date=new Date(item.savedAt).toLocaleString("nl-NL");main.innerHTML=`<strong>${escapeHtml(item.caseCode)}</strong><small>${escapeHtml(item.location)} · opgeslagen ${date} · ${item.yesCount} positieve waarnemingen</small>`;const chips=document.createElement("div");chips.className="history-profiles";item.profiles.forEach(p=>{const chip=document.createElement("span");chip.className="history-chip";chip.textContent=`${p.title}: ${p.match===null?"—":p.match+"%"}`;chips.appendChild(chip);});main.appendChild(chips);const del=document.createElement("button");del.type="button";del.textContent="Verwijder";del.addEventListener("click",()=>{saveHistory(loadHistory().filter(x=>x.id!==item.id));renderHistory();showToast("Check uit overzicht verwijderd.");});row.append(main,del);host.appendChild(row);});}
  function renderReport(){const snap=M.createSnapshot(state,catalog);$("reportPreview").textContent=M.reportText(snap);$("reportState").textContent="Actueel · versie "+M.VERSION;renderProfiles("reportProfileCards");return snap;}
  function downloadText(){const snap=renderReport(),blob=new Blob(["\uFEFF"+M.reportText(snap)],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="rapport-van-bevindingen-"+snap.generatedAt.replace(/[:.]/g,"-")+".txt";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function resetSession(){if(state.dirty&&!confirm("Nieuwe check starten en huidige niet-opgeslagen invoer wissen?"))return;state=M.createState(catalog);syncContext();renderProfiles();updateSummary();goHome();showToast("Nieuwe check gestart.");}
  function syncSettingsUi(){applyTheme();$("pushToggle").checked=Boolean(settings.pushNotifications);$("inAppToggle").checked=Boolean(settings.inAppNotifications);$("settingsStatus").textContent=settings.pushNotifications&&("Notification" in window)&&Notification.permission==="denied"?"Browsermeldingen zijn in de browser geblokkeerd.":"";}
  async function togglePush(enabled){if(!enabled){settings.pushNotifications=false;saveSettings();return;}if(!("Notification" in window)){settings.pushNotifications=false;$("pushToggle").checked=false;$("settingsStatus").textContent="Deze browser ondersteunt geen meldingen.";return;}const permission=Notification.permission==="default"?await Notification.requestPermission():Notification.permission;settings.pushNotifications=permission==="granted";$("pushToggle").checked=settings.pushNotifications;saveSettings();$("settingsStatus").textContent=permission==="granted"?"Lokale browsermeldingen ingeschakeld. Remote push is in dit prototype nog niet gekoppeld.":"Meldingstoestemming niet verleend.";}
  async function setupPwa(){window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("installBtn").hidden=false;});$("installBtn").addEventListener("click",async()=>{if(!installPrompt)return;const p=installPrompt;installPrompt=null;$("installBtn").hidden=true;try{await p.prompt();await p.userChoice;}catch(_){}});if(!("serviceWorker" in navigator)||!window.isSecureContext){$("offlineStatus").textContent="Offlinegebruik vereist HTTPS of localhost.";return;}try{await navigator.serviceWorker.register("./sw.js",{scope:"./",updateViaCache:"none"});await navigator.serviceWorker.ready;$("offlineStatus").textContent="Appbestanden zijn beschikbaar voor offlinegebruik. Overzicht en instellingen worden lokaal bewaard.";}catch(_){$("offlineStatus").textContent="Offlinevoorbereiding is niet gelukt.";}}
  function bindButtons(){$("homeBtn").addEventListener("click",goHome);all("[data-home]").forEach(b=>b.addEventListener("click",goHome));all("[data-open]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.open)));$("openObservationsBtn").onclick=()=>showView("observationsView");$("openControlBtn").onclick=()=>showView("controlView");$("openCovertBtn").onclick=()=>showView("covertView");$("openOverviewBtn").onclick=()=>showView("overviewView");$("openReportBtn").onclick=()=>showView("reportView");$("openSettingsBtn").onclick=()=>showView("settingsView");$("resumeBtn").onclick=()=>showView("observationsView");$("controlToObservationsBtn").onclick=()=>showView("observationsView");$("covertToReportBtn").onclick=()=>showView("reportView");$("observationsReportBtn").onclick=()=>showView("reportView");$("saveCheckBtn").onclick=saveCurrentCheck;$("clearObservationsBtn").onclick=clearObservations;$("clearHistoryBtn").onclick=()=>{if(confirm("Alle lokaal opgeslagen checks uit het overzicht wissen?")){saveHistory([]);renderHistory();showToast("Overzicht gewist.");}};$("buildReportBtn").onclick=renderReport;$("downloadTextBtn").onclick=downloadText;$("printBtn").onclick=()=>{renderReport();window.print();};$("resetBtn").onclick=resetSession;all("[data-mobile]").forEach(b=>b.onclick=()=>showView(b.dataset.mobile));all('input[name="theme"]').forEach(el=>el.addEventListener("change",()=>{if(el.checked){settings.theme=el.value;saveSettings();applyTheme();showToast("Thema aangepast.");}}));$("pushToggle").addEventListener("change",()=>togglePush($("pushToggle").checked));$("inAppToggle").addEventListener("change",()=>{settings.inAppNotifications=$("inAppToggle").checked;saveSettings();if(settings.inAppNotifications)showToast("In-app meldingen ingeschakeld.");});}
  function init(){applyTheme();bindContext();bindButtons();syncContext();renderProfiles();updateSummary();renderHistory();syncSettingsUi();showView("homeView");setupPwa();window.addEventListener("beforeprint",renderReport);window.addEventListener("beforeunload",e=>{if(state.dirty){e.preventDefault();e.returnValue="";}});}
  window.addEventListener("DOMContentLoaded",init);
})();
