"use strict";
const fs=require("node:fs"),path=require("node:path");
const assert=(v,m)=>{if(!v)throw new Error(m);};
const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");
const css=fs.readFileSync(path.join(__dirname,"../app-v4.css"),"utf8");
const signals=fs.readFileSync(path.join(__dirname,"../signals.js"),"utf8");
assert(html.includes('id="openObservationsBtn"'),"Waarnemingentegel ontbreekt");
assert(html.includes('id="openControlBtn"'),"Controletegel ontbreekt");
assert(html.includes('id="openCovertBtn"'),"Heimelijke tegel ontbreekt");
assert(html.includes('id="openOverviewBtn"'),"Overzichtstegel ontbreekt");
assert(html.includes('id="openSettingsBtn"'),"Instellingentegel ontbreekt");
assert(html.includes('id="pushToggle"')&&html.includes('id="inAppToggle"'),"Meldingsinstellingen ontbreken");
assert(html.includes('name="theme"')&&html.includes('value="dark"'),"Donker thema ontbreekt");
assert(!html.includes('id="includeArbeid"')&&!html.includes('id="includeSeksueel"')&&!html.includes('id="includeCrimineel"'),"Oude drie-modulekeuze nog aanwezig");
assert(!signals.includes('type:"general"'),"Algemene signalen nog in catalogus");
assert(signals.includes('type:"environment"'),"Omgevingssignalen ontbreken");
assert(css.includes('html[data-theme="dark"]'),"Donkere visualisatie ontbreekt");
console.log("UI-regressies geslaagd: v4-homepage, één waarnemingenlijst, overzicht en instellingen aanwezig.");
